-- Oracle Database Schema for Secure File Storage Platform
-- Run these commands as your Oracle user to create the required tables

-- Create Users table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(80) NOT NULL UNIQUE,
    email VARCHAR2(120) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    two_factor_secret VARCHAR2(32),
    two_factor_enabled NUMBER(1) DEFAULT 0 CHECK (two_factor_enabled IN (0,1))
);

-- Create File Records table
CREATE TABLE file_records (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR2(255) NOT NULL,
    stored_filename VARCHAR2(255) NOT NULL,
    user_id NUMBER NOT NULL,
    file_size NUMBER NOT NULL,
    encryption_key CLOB NOT NULL,
    upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_file_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Create Activity Logs table
CREATE TABLE activity_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    action VARCHAR2(50) NOT NULL,
    description CLOB,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_activity_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Create Share Links table
CREATE TABLE share_links (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR2(64) NOT NULL UNIQUE,
    file_id NUMBER NOT NULL,
    created_by NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    downloads NUMBER DEFAULT 0,
    CONSTRAINT fk_share_file FOREIGN KEY (file_id) REFERENCES file_records(id) ON DELETE CASCADE,
    CONSTRAINT fk_share_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

-- Create indexes for better performance
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_file_records_user_id ON file_records(user_id);
CREATE INDEX idx_activity_logs_user_id ON activity_logs(user_id);
CREATE INDEX idx_share_links_token ON share_links(token);
CREATE INDEX idx_share_links_expires ON share_links(expires_at);

-- Grant necessary privileges (adjust as needed for your Oracle setup)
-- GRANT CONNECT, RESOURCE TO your_username;
-- GRANT CREATE SESSION TO your_username;

COMMIT;
